### ISSUE TITLE
Wrong distance calculated

### ISSUE THREAD

**Issue by bobvanluijt** [gaspiman/cosine_similarity#1]
https://play.golang.org/p/dRwrMgXPjJ1

Should returns 0 but returns 1.

**Comment by bgokden** [comment]
Hi @bobvanluijt , 

Just to be clear it should return 1. 
This is Cosine Similarity function for cosine distance you need to distract it from 1 as 

cosine distance = 1 - cosine similarity

**Comment by bobvanluijt** [comment]
I see, thanks @bgokden
